#!/bin/sh

if [ -d "$HOME/.oh-my-zsh" ]; then
  echo "Oh-my-zsh already installed"
else
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
