#!/bin/sh

set -x

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  echo "Installing Vim Plugins"

  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  vim -es -u .vimrc -i NONE -c "PlugInstall" -c "qa" 2>&1
  exit 0
fi
